"""Small service contracts for future provider and repository implementations."""
from typing import Protocol


class TextProvider(Protocol):
    def text(self,prompt:str,system:str,model:str|None=None)->tuple[str,str]:...
    def check(self)->dict:...
    def status(self)->dict:...


class ContentRepository(Protocol):
    def save(self,data:dict)->dict:...
    def get(self,id:str,version:int|None=None)->dict:...
    def list(self,query:str='',kind:str='',domain:str='')->list[dict]:...
    def versions(self,id:str)->list[dict]:...
    def save_project(self,data:dict)->dict:...
    def project(self,id:str)->dict:...


class AccountRepository(Protocol):
    def register(self,email:str,password:str,name:str)->dict:...
    def authenticate(self,email:str,password:str)->dict:...
    def get(self,id:str)->dict|None:...
    def root(self,user:dict):...

